#!/bin/bash

# Structure of selection: IF

# Status of a file

test_file(){

FILE=~/.bashrc


if[ -e "$FILE"]; then
    if [ -f "$FILE" ]; then
	echo "$FILE is a regular file"
    fi

    if [ -d "$FILE"]; then
	echo "$FILE is a directory"
    fi

    if [ -r "$FILE"]; then
	echo "$FILE is a file readable"
    fi

    if [ -w "$FILE"]; then
	echo "$FILE is a file writable"
    fi

    if [ -x "$FILE"]; then
	echo "$FILE is a file executable/searchable"
    fi

else
    echo "$FILE doesn't exist"
    return 1
fi


}
       
